#!/usr/bin/env bash
SCALA_VERSION=2.9.2
MAVEN_REPO=$HOME/.m2/repository
SCALA_LIB=$MAVEN_REPO/org/scala-lang/scala-library/$SCALA_VERSION/scala-library-$SCALA_VERSION.jar
CLASSPATH=$PWD/target/classes:$SCALA_LIB
MAIN_CLASS="net.aethersanctum.fractus.FractusMain"
echo "java -cp $CLASSPATH \"$MAIN_CLASS\" $*"
java -cp $CLASSPATH -Xmx1024m "$MAIN_CLASS" $*
